stages :
  - build
  - test
  - release

build-project:
  stage : build
  tags:
    - ktb_windows
  script:
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake -S .. -B .
    - cmake --build .
#    - make
#    - pwd
    - ./ktb
